### ISSUE TITLE
why lightglue+superpoint is better than  LightGlue+disk?

### ISSUE THREAD

**Issue by zebin-dm** [cvg/LightGlue#19]
In my experiment， lightglue+superpoint is better than  LightGlue + disk，which is not consistent with lightglue paper:

**Comment by Phil26AT** [comment]
Hi, we also obtained similar results on the IMC 2023 benchmark, where SP+LG worked best. DISK performs exceptionally well on phototourism data (on which it was trained and evaluated), but less good on other data. This suggests that it suffers a bit from over-fitting. Retraining it with more data (DISK only requires posed images instead of dense depth) might solve this generalization gap.
