### ISSUE TITLE
can you offer train dataset?

### ISSUE THREAD

**Issue by chenxianbo** [cvg/LightGlue#39]
In the paper, there are two datasets, can you offer them?  So when you release the train code,  I can train immediately
1. "first pre-train LightGlue on synthetic homographies of real-images"
2, "We use 170k images from the Oxford-Pairs 1M distractors dataset, and split them into 150K/10K/10K images for training/validation/test"

**Comment by Phil26AT** [comment]
Hey @chenxianbo, thank you for your interest in LightGlue.

The data can be downloaded using this script: https://github.com/filipradenovic/revisitop/blob/master/python/download.py

The release of the training code is a bit delayed because of other responsibilities, but we push hard to release it ASAP!

**Comment by vrk7** [comment]
@Phil26AT - Do you have any dates by which we can expect the same?

**Comment by sarlinpe** [comment]
It's now released: https://github.com/cvg/glue-factory
